Web_Development/Django_Ecommerce_Site/addresses/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^create/$',views.checkout_address_create_view,name='checkout_address_create'),
    url(r'^reuse/$',views.checkout_address_reuse_view,name='checkout_address_reuse'),
]

Web_Development/Django_Ecommerce_Site/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$',views.cart_home,name='home'),
    url(r'^checkout/$',views.checkout_home,name='checkout'),
    url(r'^update/$',views.cart_update,name='update'),
]

Web_Development/Django_Ecommerce_Site/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^products/',include('products.urls',namespace='products')),
    url(r'^search/',include('search.urls',namespace='search')),  
    url(r'^cart/',include('cart.urls',namespace='cart')),  
    url(r'^order/',include('orders.urls',namespace='order')),
    url(r'^checkout_address/',include('addresses.urls',namespace='addresses')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Web_Development/Django_Ecommerce_Site/cart/models.py
from django.db import models
from django.conf import settings

from products.models import Product
from django.db.models.signals import m2m_changed
User=settings.AUTH_USER_MODEL

# Create your models here.
class CartManager(models.Manager):
    def new_or_get(self,request):
        cart_id=request.session.get('cart_id',None)
        qs=self.get_queryset().filter(id=cart_id)
        if qs.count()==1:
            new_obj=False
            cart_obj=qs.first()
            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user=request.user
                cart_obj.save()
        else:
            cart_obj=Cart.objects.new(user=request.user)
            new_obj=True
            request.session['cart_id']=cart_obj.id
        return cart_obj,new_obj
    def new(self,user=None):
        user_obj=None
        if user is not None:
            if user.is_authenticated():
                user_obj=user
        return self.model.objects.create(user=user_obj)
        
class Cart(models.Model):
    user=models.ForeignKey(User,null=True,blank=True)
    products=models.ManyToManyField(Product,blank=True)
    total=models.DecimalField(default=0.00,max_digits=100,decimal_places=2)
    updated=models.DateTimeField(auto_now=True)
    timestamp=models.DateTimeField(auto_now_add=True)

    objects=CartManager()

    def __str__(self):
        return str(self.id)

def pre_save_cart_receiver(sender,instance,action,*args,**kwargs):
    if action=='post_add'or action=='post_remove' or action=='post_clear':
        products=instance.products.all()
        total=0
        for x in products:
            total+=x.price
        instance.total=total
        instance.save()

m2m_changed.connect(pre_save_cart_receiver,sender=Cart.products.through)

Web_Development/Django_Ecommerce_Site/cart/views.py
from django.shortcuts import render,redirect
from .models import Cart
from orders.models import Order
from products.models import Product
from accounts.forms import LoginForm,GuestForm
from addresses.forms import AddressForm
from addresses.models import Address
from accounts.models import GuestEmail
from billing.models import BillingProfile
# Create your views here.

def cart_home(request):
    cart_obj,new_obj=Cart.objects.new_or_get(request)
    return render(request,'cart/home.html',{"cart":cart_obj})

def cart_update(request):
    product_id=request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj=Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print('Product Error!')
            return redirect('cart:home')
        # except:
        #     print('Unknown Error!!')
        #     return redirect('cart:home')
        cart_obj,new_obj=Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
        else:
            cart_obj.products.add(product_obj)
    else:
        print('hacked')
    return redirect('cart:home')

def checkout_home(request):
    cart_obj,cart_created=Cart.objects.new_or_get(request)
    order_obj=None
    address_qs=None
    if cart_created or cart_obj.products.count()==0:
        return redirect('cart:home')

    login_form=LoginForm()
    guest_form=GuestForm()
    address_form=AddressForm()
    
    shipping_address_id=request.session.get('shipping_address_id',None)
    billing_address_id=request.session.get('billing_address_id',None)

    billing_profile,billing_profile_created=BillingProfile.objects.new_or_get(request)

    if billing_profile is not None:
        if request.user.is_authenticated():
            address_qs=Address.objects.filter(billing_profile=billing_profile)
        order_obj,order_obj_created=Order.objects.new_or_get(billing_profile,cart_obj)
        if shipping_address_id:
            order_obj.shipping_address=Address.objects.get(id=shipping_address_id)  
            del request.session['shipping_address_id']
        if billing_address_id:
            order_obj.billing_address=Address.objects.get(id=billing_address_id) 
            del request.session['billing_address_id']
        if billing_address_id or shipping_address_id:
            order_obj.save()

    

    if request.method == "POST":
        is_done=order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            del request.session['cart_id']
            return redirect('/products')
            
    context={
        'object':order_obj,
        'billing_profile':billing_profile,
        'login_form':login_form,
        'guest_form':guest_form,
        'address_form':address_form,
        'address_qs':address_qs,
    }
    return render(request,'cart/checkout.html',context)

Web_Development/Django_Ecommerce_Site/cart/templates/cart/checkout.html
{% extends "base.html" %}
{% block content %}
{% if not billing_profile %}
<div class="row text-center">
  <div class="col-12 col-md-6">
    <p class="lead">Login</p>
    {% include "snippets/login.html" with form=login_form next_url=request.build_absolute_uri %}
  </div>
  <div class="col-12 col-md-6">
    <p class="lead">continue as guest</p>
    {% url 'guest_register' as guest_register_url  %}
    {% include "snippets/login.html" with form=guest_form next_url=request.build_absolute_uri  action_url=guest_register_url %}
  </div>
</div>
{% else %}
  {% if not object.shipping_address %}
  
  <div class="row">
    <div class="col-12">
      <p class="lead">Shipping Address</p>
      <hr>
    </div>
    <div class='col-6'>
      {% url 'addresses:checkout_address_create' as checkout_address_create  %}
      {% include "addresses/form.html" with form=address_form next_url=request.build_absolute_uri  action_url=checkout_address_create address_type='shipping' %}
    </div>
    {%if address_qs.exists%}
    {% url 'addresses:checkout_address_reuse' as checkout_address_reuse  %}
    {% include "addresses/address.html" with address_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_reuse %}
    {%endif%}
    </div>
  </div>

  {% elif not object.billing_address %}
  <div class="row">
    <div class="col-12">
      <p class="lead">Billing Address</p>
      <hr>
    </div>
    <div class='col-6'>
      {% include "addresses/form.html" with form=address_form next_url=request.build_absolute_uri  action_url=checkout_address_create address_type='billing' %}
    </div>
    {% if address_qs.exists %}
    {% url 'addresses:checkout_address_reuse' as checkout_address_reuse  %}
    {% include "addresses/address.html" with address_qs=address_qs next_url=request.build_absolute_uri address_type='billing' action_url=checkout_address_reuse %}
    {% endif %}
    </div>
  </div>
  {% else %}
  <h1>Checkout</h1>
  <p>Cart Total: {{object.cart.total}}</p>
  <p>Shipping Total: {{object.shipping_total}}</p>
  <p>Order Total: {{object.total}}</p>
  <form class='form' method='POST' action=''>
  {% csrf_token %}
  <button type='submit' class='btn btn-primary'>Checkout</button>
  </form>
  {% endif %}
    
{% endif %}


{% endblock content %}

Web_Development/Django_Ecommerce_Site/cart/templates/cart/home.html
{% extends "base.html" %}
{% block content %}
  <h1>Cart</h1>
  {% if cart.products.exists %}
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Product Name</th>
          <th>Product Price</th>
        </tr>
      </thead>
      <tbody>
        {% for product in cart.products.all %}
          <tr>
            <th scope="row" >{{forloop.counter}}</th>
            <td>
              {{product.title}} {% include "products/update.html" with product=product cart=cart in_cart=True %}
            </td>
            <td>{{product.price}}</td>
          </tr>
        {% endfor %}
        <tr>
          <td colspan="2" ><b>Total: </b></td>
          <td>{{cart.total}}</td>
        </tr>
        <tr>
            <td colspan="2" ></td>
            <td><a class="btn btn-lg btn-success" href="{%url 'cart:checkout' %}">CheckOut</a></td>
          </tr>
      </tbody>
    </table>
  {% else %}
    <p class="lead" >Cart is empty</p>
  {% endif %}
{% endblock content %}