Web_Development/Django_Ecommerce_Site/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$',views.cart_home,name='home'),
    url(r'^checkout/$',views.checkout_home,name='checkout'),
    url(r'^update/$',views.cart_update,name='update'),
]

Web_Development/Django_Ecommerce_Site/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^products/',include('products.urls',namespace='products')),
    url(r'^search/',include('search.urls',namespace='search')),  
    url(r'^cart/',include('cart.urls',namespace='cart')),  
    url(r'^order/',include('orders.urls',namespace='order')),
    url(r'^checkout_address/',include('addresses.urls',namespace='addresses')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Web_Development/Django_Ecommerce_Site/products/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$',views.ProductListView.as_view(),name='home'),
    url(r'^(?P<slug>[\w-]+)/$',views.ProductDetailView.as_view(),name='detail'),
]

Web_Development/Django_Ecommerce_Site/products/models.py
from django.db import models
from django.db.models import Q
from mysite.utils import unique_slug_generator
from django.shortcuts import reverse
from django.db.models.signals import pre_save,post_save
# Create your models here.
class ProductQuerySet(models.query.QuerySet):

    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True,active=True)

    def searched(self,query):
        lookups=Q(title__icontains=query)|Q(description__icontains=query)|Q(tag__title__icontains=query)
        return Product.objects.filter(lookups).distinct()

class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model,using=self._db)
    
    def all(self):
        return self.get_queryset().active()

    def features(self):
        return self.get_queryset().featured()

    def get_by_id(self,id):
        qs=self.get_queryset().filter(id=id)
        if qs.count()==1:
            return qs.first()
        return None

    def searches(self,query):
        return self.get_queryset().active().searched(query)

class Product(models.Model):
    title=models.CharField(max_length=120)
    slug=models.SlugField(blank=True,unique=True)
    image=models.ImageField(upload_to='products',null=True,blank=True)
    description=models.TextField()
    price=models.DecimalField(decimal_places=2,max_digits=20,default=20.99)
    featured=models.BooleanField(default=False)
    active=models.BooleanField(default=True)

    objects=ProductManager()

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'slug':self.slug})
    def __str__(self):
        return self.title

def product_pre_save_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug=unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver,sender=Product)

Web_Development/Django_Ecommerce_Site/products/views.py
from django.shortcuts import render,Http404,get_object_or_404
from django.views.generic import ListView,DetailView
from .models import Product

from cart.models import Cart

# Create your views here.
class ProductListView(ListView):
    def get_queryset(self,*args,**kwargs):
        request=self.request
        return Product.objects.all()


class ProductDetailView(DetailView):
    #queryset=Product.objects.all()

    def get_context_data(self,*args,**kwargs):
        context=super(ProductDetailView,self).get_context_data(*args,**kwargs)
        cart_obj,new_obj=Cart.objects.new_or_get(self.request)
        context['cart']=cart_obj
        return context

    def get_object(self,*args,**kwargs):
        request=self.request
        slug=self.kwargs.get('slug')
        #pk=self.kwargs.get('pk')
        try:
            instance=get_object_or_404(Product,slug=slug,active=True)
        except Product.DoesNotExist:
            raise Http404('Not Found...')
        except Product.MultipleObjectsReturned:
            qs=Product.objects.filter(slug=slug,active=True)
            instance=qs.first()
        except:
            raise Http404('UnKnown Error!!!')
        if instance is None:
            raise Http404('Product doesnt exist')
        return instance

Web_Development/Django_Ecommerce_Site/products/templates/products/product_detail.html
{% extends "base.html" %}
{% block content %}
<div class="row">
  <div class="col-12 col-md-6">
    {% if product.image %}
      <img src="{{product.image.url}}" alt="image" width="250px">
    {% endif %}
    {{product.title}} <br>
  </div>
  <div class="col-12 col-md-6">
    {% include "products/update.html" with product=object cart=cart %}    
  </div>
</div>

    
{% endblock content %}

Web_Development/Django_Ecommerce_Site/products/templates/products/product_list.html
{% extends "base.html" %}
{% block content %}
  {% for product in product_list %}
    <a href="{{product.get_absolute_url}}">{{product.title}}</a>  <br>
  {% endfor %}
{% endblock content %} 

Web_Development/Django_Ecommerce_Site/products/templates/products/update.html
<form action="{% url 'cart:update'  %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="product_id" value='{{product.id}}'>
    {% if in_cart %}
        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
    {% else %}
        {% if object in cart.products.all %}
            <button type="submit" class="btn btn-danger">Remove</button>
        {% else %}
            <button type="submit" class="btn btn-success">Add to cart</button>
        {% endif %}
    {% endif %}
</form>